"""Integration test: real audio pipeline proof (Sprint 02).

Proves that real FLAC files flow through scan → resolve → plan → apply
with MutagenTagWriter, and that tags can be read back with mutagen.

No .meta.json sidecars are used as substitutes for audio content.
No FakerContext. No empty stub files. No live API calls.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import asdict
from pathlib import Path

import mutagen
import pytest

from resonance.core.enricher import build_tag_patch
from resonance.core.identifier import (
    ConfidenceTier,
    DirectoryEvidence,
    ProviderCapabilities,
    ProviderRelease,
    ProviderTrack,
    extract_evidence,
)
from resonance.core.planner import Plan, plan_directory
from resonance.core.resolver import resolve_directory
from resonance.core.state import DirectoryRecord, DirectoryState
from resonance.core.applier import apply_plan, ApplyStatus
from resonance.infrastructure.directory_store import DirectoryStateStore
from resonance.infrastructure.scanner import LibraryScanner
from resonance.services.tag_writer import MutagenTagWriter

# ---------------------------------------------------------------------------
# Fixtures directory (real FLAC files generated by ffmpeg)
# ---------------------------------------------------------------------------
FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "real_audio"


# ---------------------------------------------------------------------------
# Pre-cached provider response (no live API calls)
# ---------------------------------------------------------------------------
ALBUM1_RELEASE = ProviderRelease(
    provider="musicbrainz",
    release_id="test-mb-release-001",
    title="Integration Test Album",
    artist="Test Artist",
    tracks=(
        ProviderTrack(
            position=1,
            title="First Track",
            duration_seconds=3,
            fingerprint_id="fp-album1-001",
            composer=None,
            disc_number=1,
            recording_id="rec-001",
        ),
        ProviderTrack(
            position=2,
            title="Second Track",
            duration_seconds=4,
            fingerprint_id="fp-album1-002",
            composer=None,
            disc_number=1,
            recording_id="rec-002",
        ),
        ProviderTrack(
            position=3,
            title="Third Track",
            duration_seconds=5,
            fingerprint_id="fp-album1-003",
            composer=None,
            disc_number=1,
            recording_id="rec-003",
        ),
    ),
    year=2025,
)


class StubProviderClient:
    """Pre-cached provider client — returns deterministic results, no API calls."""

    def __init__(self, release: ProviderRelease) -> None:
        self._release = release

    @property
    def capabilities(self) -> ProviderCapabilities:
        # Fingerprints only — avoids metadata search deduplication issue
        return ProviderCapabilities(supports_fingerprints=True, supports_metadata=False)

    def search_by_fingerprints(self, fingerprints: list[str]) -> list[ProviderRelease]:
        return [self._release]

    def search_by_metadata(
        self, artist: str | None, album: str | None, track_count: int
    ) -> list[ProviderRelease]:
        return []

    def release_by_id(self, provider: str, release_id: str) -> ProviderRelease | None:
        if release_id == self._release.release_id:
            return self._release
        return None


def _stable_plan_hash(plan: Plan) -> str:
    """Reproduce the plan hash used by enricher for record_plan_summary."""
    payload = asdict(plan)

    def convert_paths(obj):
        if isinstance(obj, Path):
            return str(obj)
        if isinstance(obj, dict):
            return {k: convert_paths(v) for k, v in obj.items()}
        if isinstance(obj, (list, tuple)):
            return [convert_paths(item) for item in obj]
        return obj

    payload = convert_paths(payload)
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Fingerprint reader that returns deterministic IDs matching the stub release
# ---------------------------------------------------------------------------
def _make_fingerprint_reader(audio_files: list[Path], release: ProviderRelease):
    """Build a fingerprint reader mapping sorted files → release track fingerprints."""
    sorted_files = sorted(audio_files)
    ordered_tracks = sorted(release.tracks, key=lambda t: t.position)
    fp_map = {}
    for path, track in zip(sorted_files, ordered_tracks):
        fp_map[path.resolve()] = track.fingerprint_id
    return lambda p: fp_map.get(p.resolve())


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.fixture
def work_dir(tmp_path: Path) -> Path:
    """Copy real audio fixtures into a temporary working directory."""
    src = FIXTURE_DIR / "album1"
    assert src.exists(), f"Fixture directory missing: {src}"
    dest = tmp_path / "library" / "album1"
    shutil.copytree(src, dest)
    return tmp_path


def test_real_audio_scan_resolve_plan_apply_readback(work_dir: Path) -> None:
    """Full pipeline: scan → resolve → plan → apply → tag readback on real FLAC."""
    library = work_dir / "library"
    album_dir = library / "album1"
    state_db = work_dir / "state.db"

    # ── 1. Scan ──────────────────────────────────────────────────────────
    scanner = LibraryScanner(roots=[library])
    batches = list(scanner.iter_directories())
    assert len(batches) == 1, f"Expected 1 directory batch, got {len(batches)}"
    batch = batches[0]
    assert len(batch.files) == 3, f"Expected 3 audio files, got {len(batch.files)}"

    # Verify files are real audio (non-zero, readable by mutagen)
    for f in batch.files:
        audio = mutagen.File(str(f))
        assert audio is not None, f"mutagen cannot read {f}"
        assert audio.info.length > 0, f"Zero-length audio: {f}"

    # ── 2. Resolve ───────────────────────────────────────────────────────
    store = DirectoryStateStore(state_db)
    try:
        # Extract evidence with a fingerprint reader that maps to our stub release
        fp_reader = _make_fingerprint_reader(batch.files, ALBUM1_RELEASE)
        evidence = extract_evidence(batch.files, fingerprint_reader=fp_reader)
        assert evidence.track_count == 3

        provider = StubProviderClient(ALBUM1_RELEASE)
        outcome = resolve_directory(
            dir_id=batch.dir_id,
            path=batch.directory,
            signature_hash=batch.signature_hash,
            evidence=evidence,
            store=store,
            provider_client=provider,
        )
        assert outcome.state == DirectoryState.RESOLVED_AUTO, (
            f"Expected RESOLVED_AUTO, got {outcome.state}"
        )

        # ── 3. Plan ─────────────────────────────────────────────────────
        record = store.get(batch.dir_id)
        assert record is not None
        assert record.state == DirectoryState.RESOLVED_AUTO

        plan = plan_directory(
            record=record,
            pinned_release=ALBUM1_RELEASE,
            source_files=batch.files,
        )
        assert len(plan.operations) == 3

        # Transition to PLANNED (required by apply_plan preflight)
        store.set_state(
            batch.dir_id,
            DirectoryState.PLANNED,
            pinned_provider=ALBUM1_RELEASE.provider,
            pinned_release_id=ALBUM1_RELEASE.release_id,
        )
        store.record_plan_summary(
            batch.dir_id,
            plan_hash=_stable_plan_hash(plan),
            plan_version=plan.plan_version,
        )

        # ── 4. Build tag patch ───────────────────────────────────────────
        tag_patch = build_tag_patch(
            plan=plan,
            pinned_release=ALBUM1_RELEASE,
            resolution_state=DirectoryState.RESOLVED_AUTO,
        )
        assert tag_patch.allowed is True

        # ── 5. Apply with MutagenTagWriter (real tag writes) ────────────
        tag_writer = MutagenTagWriter()
        report = apply_plan(
            plan=plan,
            tag_patch=tag_patch,
            store=store,
            allowed_roots=(work_dir,),
            dry_run=False,
            tag_writer=tag_writer,
        )
        assert report.status == ApplyStatus.APPLIED, (
            f"Apply failed: {report.errors}"
        )
        assert not report.errors
        assert len(report.tag_ops) == 3

        # ── 6. Read tags back with mutagen directly ──────────────────────
        for op in sorted(plan.operations, key=lambda o: o.track_position):
            dest = _resolve_dest(op.destination_path, work_dir)
            audio = mutagen.File(str(dest))
            assert audio is not None, f"mutagen cannot read applied file {dest}"

            # FLAC stores Vorbis comments — keys are uppercase
            tags = {k.lower(): v[0] if isinstance(v, list) else v for k, v in audio.tags.items()}

            # Album-level tags
            assert tags["album"] == "Integration Test Album", (
                f"album mismatch: {tags.get('album')}"
            )
            assert tags["albumartist"] == "Test Artist", (
                f"albumartist mismatch: {tags.get('albumartist')}"
            )

            # Track-level tags
            expected_track = next(
                t for t in ALBUM1_RELEASE.tracks if t.position == op.track_position
            )
            assert tags["title"] == expected_track.title, (
                f"title mismatch on track {op.track_position}: "
                f"got {tags.get('title')!r}, expected {expected_track.title!r}"
            )
            assert tags["tracknumber"] == str(op.track_position), (
                f"tracknumber mismatch: {tags.get('tracknumber')}"
            )

            # MusicBrainz IDs
            assert tags.get("musicbrainz_albumid") == ALBUM1_RELEASE.release_id
            if expected_track.recording_id:
                assert tags.get("musicbrainz_recordingid") == str(expected_track.recording_id)

            # Provenance tags (prove write happened)
            assert "resonance.prov.version" in tags
            assert tags["resonance.prov.pinned_provider"] == "musicbrainz"

        # ── 7. Verify state transition ───────────────────────────────────
        final_record = store.get(batch.dir_id)
        assert final_record is not None
        assert final_record.state == DirectoryState.APPLIED

    finally:
        store.close()


# ---------------------------------------------------------------------------
# Album 2: two-track release (different track count proves pipeline handles it)
# ---------------------------------------------------------------------------
ALBUM2_RELEASE = ProviderRelease(
    provider="musicbrainz",
    release_id="test-mb-release-002",
    title="Short EP",
    artist="EP Artist",
    tracks=(
        ProviderTrack(
            position=1,
            title="Side A",
            duration_seconds=3,
            fingerprint_id="fp-album2-001",
            composer=None,
            disc_number=1,
            recording_id="rec-ep-001",
        ),
        ProviderTrack(
            position=2,
            title="Side B",
            duration_seconds=4,
            fingerprint_id="fp-album2-002",
            composer=None,
            disc_number=1,
            recording_id="rec-ep-002",
        ),
    ),
    year=2026,
)


@pytest.fixture
def work_dir_album2(tmp_path: Path) -> Path:
    """Copy album2 real audio fixtures into a temporary working directory."""
    src = FIXTURE_DIR / "album2"
    assert src.exists(), f"Fixture directory missing: {src}"
    dest = tmp_path / "library" / "album2"
    shutil.copytree(src, dest)
    return tmp_path


def test_real_audio_two_track_ep(work_dir_album2: Path) -> None:
    """Pipeline proof for a 2-track EP — different shape than album1's 3 tracks."""
    library = work_dir_album2 / "library"
    album_dir = library / "album2"
    state_db = work_dir_album2 / "state.db"

    scanner = LibraryScanner(roots=[library])
    batches = list(scanner.iter_directories())
    assert len(batches) == 1
    batch = batches[0]
    assert len(batch.files) == 2

    for f in batch.files:
        audio = mutagen.File(str(f))
        assert audio is not None, f"mutagen cannot read {f}"

    store = DirectoryStateStore(state_db)
    try:
        fp_reader = _make_fingerprint_reader(batch.files, ALBUM2_RELEASE)
        evidence = extract_evidence(batch.files, fingerprint_reader=fp_reader)
        assert evidence.track_count == 2

        provider = StubProviderClient(ALBUM2_RELEASE)
        outcome = resolve_directory(
            dir_id=batch.dir_id,
            path=batch.directory,
            signature_hash=batch.signature_hash,
            evidence=evidence,
            store=store,
            provider_client=provider,
        )
        assert outcome.state == DirectoryState.RESOLVED_AUTO

        record = store.get(batch.dir_id)
        assert record is not None
        plan = plan_directory(
            record=record,
            pinned_release=ALBUM2_RELEASE,
            source_files=batch.files,
        )
        assert len(plan.operations) == 2

        store.set_state(
            batch.dir_id,
            DirectoryState.PLANNED,
            pinned_provider=ALBUM2_RELEASE.provider,
            pinned_release_id=ALBUM2_RELEASE.release_id,
        )
        store.record_plan_summary(
            batch.dir_id,
            plan_hash=_stable_plan_hash(plan),
            plan_version=plan.plan_version,
        )

        tag_patch = build_tag_patch(
            plan=plan,
            pinned_release=ALBUM2_RELEASE,
            resolution_state=DirectoryState.RESOLVED_AUTO,
        )
        assert tag_patch.allowed is True

        tag_writer = MutagenTagWriter()
        report = apply_plan(
            plan=plan,
            tag_patch=tag_patch,
            store=store,
            allowed_roots=(work_dir_album2,),
            dry_run=False,
            tag_writer=tag_writer,
        )
        assert report.status == ApplyStatus.APPLIED
        assert not report.errors
        assert len(report.tag_ops) == 2

        for op in sorted(plan.operations, key=lambda o: o.track_position):
            dest = _resolve_dest(op.destination_path, work_dir_album2)
            audio = mutagen.File(str(dest))
            assert audio is not None
            tags = {k.lower(): v[0] if isinstance(v, list) else v for k, v in audio.tags.items()}
            assert tags["album"] == "Short EP"
            assert tags["albumartist"] == "EP Artist"
            assert tags.get("musicbrainz_albumid") == ALBUM2_RELEASE.release_id

        final_record = store.get(batch.dir_id)
        assert final_record is not None
        assert final_record.state == DirectoryState.APPLIED
    finally:
        store.close()


def _resolve_dest(dest: Path, root: Path) -> Path:
    """Resolve a relative destination path against the working root."""
    if dest.is_absolute():
        return dest
    return root / dest
